# Generated by Django 4.0.4 on 2022-05-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySearch', '0002_alter_autocomplete_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=30, null=True)),
                ('answer', models.CharField(blank=True, max_length=30, null=True)),
                ('answer_html', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('lang', models.CharField(blank=True, max_length=30, null=True)),
                ('last_update', models.CharField(blank=True, max_length=30, null=True)),
                ('question_ar', models.CharField(blank=True, max_length=30, null=True)),
                ('answer_ar', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
