# Generated by Django 4.0.4 on 2022-05-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySearch', '0003_covid'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Youtube_link', models.CharField(blank=True, max_length=50, null=True)),
                ('ID', models.CharField(blank=True, max_length=30, null=True)),
                ('Question', models.CharField(blank=True, max_length=30, null=True)),
                ('Transcript', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
