# Generated by Django 4.0.4 on 2022-05-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySearch', '0004_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='ID',
            new_name='VID',
        ),
    ]
