# Generated by Django 4.0.4 on 2022-05-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySearch', '0005_rename_id_video_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
