# Generated by Django 4.0.4 on 2022-06-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySearch', '0006_video_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='autocomplete',
        ),
        migrations.AddField(
            model_name='video',
            name='Title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
